# For development use only

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - data:/postgresql/data
    environment:
      POSTGRES_DATABASE: ticketing
      POSTGRES_USER: ticketing
      POSTGRES_PASSWORD: password
    ports:
      - 2345:5432

volumes:
  data: